/* ─── NAV LINKS ─────────────────────────────────────────── */
export const NAV_LINKS = ["home", "about", "projects", "experience", "contact"];

/* ─── TECH STACK ────────────────────────────────────────── */
export const TECH_STACK = [
  { img: "/images/logo/js.png",          name: "JavaScript" },
  { img: "/images/logo/php.png",         name: "PHP" },
  { img: "/images/logo/bootstrap.png",   name: "Bootstrap" },
  { img: "/images/logo/tailwind.png",    name: "Tailwind CSS" },
  { img: "/images/logo/Laravel.png",     name: "Laravel" },
  { img: "/images/logo/Mysql.png",       name: "MySQL" },
  { img: "/images/logo/java.png",        name: "Java" },
  { img: "/images/logo/Firebase.png",    name: "Firebase" },
  { img: "/images/logo/supabase.png",    name: "Supabase" },
  { img: "/images/logo/React.png",       name: "React" },
  { img: "/images/logo/python.png.webp", name: "Python" },
  { img: "/images/logo/flutter.png",     name: "Flutter" },
];

/* ─── PROJECTS ──────────────────────────────────────────── */
export const PROJECTS = [
  {
    image: "/images/projects/Griya Asri Kos.png",
    title: "Kos Management System",
    label: "Web App",
    desc: "An all-in-one property management solution that automates room bookings and tenant tracking, featuring seamless Google OAuth for effortless user access.",
    badges: ["Laravel", "Tailwind", "Midtrans"],
    gradient: "from-blue-700 to-blue-400",
    featured: true,
    repo: null,
  },
  {
    image: "/images/projects/Web UKM.png",
    title: "WEBSITE UKM PENALARAN",
    label: "Web App",
    desc: "A centralized hub for academic communities to monitor workflows, featuring secure Google-integrated authentication for all organizational members.",
    badges: ["WordPress", "PHP", "MySQL"],
    gradient: "from-blue-900 to-blue-500",
    featured: true,
    repo: null,
  },
  {
    image: "/images/projects/TemuAksi.png",
    title: "TemuAksi",
    label: "Mobile",
    desc: "A high-performance mobile marketplace utilizing Google Sign-In to provide a secure and frictionless onboarding experience for social innovators.",
    badges: ["Flutter", "Firebase"],
    gradient: "from-sky-900 to-sky-400",
    featured: true,
    repo: null,
  },
  {
    image: "/images/projects/Shopping Kuy.png",
    title: "Shopping Kuy",
    label: "Web App",
    desc: "A sophisticated C2C marketplace specializing in authentic pre-loved fashion, integrating Google OAuth and RajaOngkir for seamless transactions.",
    badges: ["Laravel", "React JS", "RajaOngkir"],
    gradient: "from-violet-700 to-violet-400",
    featured: false,
    repo: null,
  },
  {
    image: "/images/projects/RentCar.png",
    title: "Rent Car",
    label: "Web App",
    desc: "A robust B2B rental solution for fleet owners, enhanced with Google SSO to ensure secure and quick access for both owners and customers.",
    badges: ["Laravel", "Bootstrap", "Midtrans"],
    gradient: "from-slate-800 to-slate-500",
    featured: false,
    repo: null,
  },
  {
    image: "/images/projects/Si PALING.png",
    title: "Si Paling",
    label: "UI/UX Design",
    desc: "A user-centric digital infrastructure for civic engagement, bridging the gap between citizens and local authorities via Google-linked reporting.",
    badges: ["Figma", "UI/UX Design"],
    gradient: "from-emerald-700 to-emerald-400",
    featured: false,
    repo: null,
  },
  {
    image: "/images/projects/Data Analyst Dashboard.png",
    title: "SalesLens Analytics",
    label: "Data Analyst",
    desc: "Transforming raw e-commerce data into actionable insights across sales, customer behavior, and product performance using Google Looker Studio.",
    badges: ["Looker Studio", "Data Analysis", "E-Commerce"],
    gradient: "from-blue-600 to-cyan-400",
    featured: false,
    repo: null,
  },
  {
    image: "/images/projects/Data Analyst.png",
    title: "FMCG Sales Analysis",
    label: "Data Analyst",
    desc: "Transforming raw FMCG transaction data into strategic BI insights, accessible via secure organizational Google Workspace integration.",
    badges: ["Power BI", "Data Analysis", "FMCG"],
    gradient: "from-yellow-600 to-orange-400",
    featured: false,
    repo: null,
  },
];

export const CERTIFICATIONS = [
  // --- COURSERA ---
  {
    provider: "Coursera",
    title: "Full Stack Web Development Professional",
    issuer: "Amazon Web Services (AWS)",
    date: "April 2026",
    credentialId: "BABFA59PQ6P1",
    credentialUrl: "https://coursera.org/verify/BABFA59PQ6P1",
    image: "/images/sertifikasi/coursera/Full Stack AWS.jpg",
  },
  {
    provider: "Coursera",
    title: "Foundation Of Coding Front End",
    issuer: "Microsoft",
    date: "May 2026",
    credentialId: "BABFA59PQ6P1",
    credentialUrl: "https://coursera.org/verify/WH2MXPLCC1PU",
    image: "/images/sertifikasi/coursera/Front End Microsoft.jpg",
  },
  {
    provider: "Coursera",
    title: "Software Engineering Mastery",
    issuer: "IBM",
    date: "Mei 2026",
    credentialId: "O4E735ED1C19",
    credentialUrl: "https://coursera.org/verify/O4E735ED1C19",
    image: "/images/sertifikasi/coursera/Software Engineer.jpg",
  },
  {
    provider: "Coursera",
    title: "Web Architecture & System Design",
    issuer: "University of London",
    date: "Mei 2026",
    credentialId: "OPIQUC835DYO",
    credentialUrl: "https://coursera.org/verify/OPIQUC835DYO",
    image: "/images/sertifikasi/coursera/Html.jpg",
  },

    // --- DICODING ---
    {
    provider: "Dicoding",
    title: "React Application Development",
    issuer: "Dicoding Academy",
    date: "Maret 2026",
    credentialId: "4EXG140QQPRL",
    credentialUrl: "https://dicoding.com/certificates/4EXG140QQPRL",
    image: "/images/sertifikasi/dicoding/membuat aplikasi react.jpg",
    },
    {
    provider: "Dicoding",
    title: "Enterprise Data Science with Microsoft Fabric",
    issuer: "Dicoding Academy",
    date: "Maret 2026",
    credentialId: "72ZDJ771LZYW",
    credentialUrl: "https://dicoding.com/certificates/72ZDJ771LZYW",
    image: "/images/sertifikasi/dicoding/data science microsoft fabric.jpg",
    },
    {
    provider: "Dicoding",
    title: "Front-End Web Architecture",
    issuer: "Dicoding Academy",
    date: "Maret 2026",
    credentialId: "KEXLQLNLWPG2",
    credentialUrl: "https://dicoding.com/certificates/KEXLQLNLWPG2",
    image: "/images/sertifikasi/dicoding/front end pemula.jpg",
    },
    {
    provider: "Dicoding",
    title: "Advanced JavaScript Programming",
    issuer: "Dicoding Academy",
    date: "Maret 2026",
    credentialId: "JLX1VW5E5Z72",
    credentialUrl: "https://dicoding.com/certificates/JLX1VW5E5Z72",
    image: "/images/sertifikasi/dicoding/Java script dicoding.jpg",
    },
    {
    provider: "Dicoding",
    title: "Python Programming Specialist",
    issuer: "Dicoding Academy",
    date: "Maret 2026",
    credentialId: "72ZDJ7K6VZYW",
    credentialUrl: "https://dicoding.com/certificates/72ZDJ7K6VZYW",
    image: "/images/sertifikasi/dicoding/python dasar.jpg",
    },
    {
    provider: "Dicoding",
    title: "Professional Web Development",
    issuer: "Dicoding Academy",
    date: "Maret 2026",
    credentialId: "OLZOYQ6M3X65",
    credentialUrl: "https://dicoding.com/certificates/OLZOYQ6M3X65",
    image: "/images/sertifikasi/dicoding/dasar pemrograman web.jpg",
    },
    {
    provider: "Dicoding",
    title: "Financial Literacy for Professionals",
    issuer: "Dicoding Academy",
    date: "Maret 2026",
    credentialId: "6RPN744M9X2M",
    credentialUrl: "https://dicoding.com/certificates/6RPN744M9X2M",
    image: "/images/sertifikasi/dicoding/financial literity.jpg",
    },

  // --- UDEMY ---
  {
    provider: "Udemy",
    title: "Full Stack Python & Django Expert",
    issuer: "Uday Academy",
    date: "Mei 2026",
    credentialId: "UC-b1e1180e-06a6-461a-91a7-b6f3f75ddce1",
    credentialUrl: "https://ude.my/UC-b1e1180e-06a6-461a-91a7-b6f3f75ddce1",
    image: "/images/sertifikasi/udemy/full stack python & djangpo.jpg",
  },
  {
    provider: "Udemy",
    title: "Full-Stack Development (React, Next.js, Node.js)",
    issuer: "Anton Voroniuk",
    date: "April 2026",
    credentialId: "UC-e151d82f-7011-4b42-b94f-9f64eecb4eaa",
    credentialUrl: "https://ude.my/UC-e151d82f-7011-4b42-b94f-9f64eecb4eaa",
    image: "/images/sertifikasi/udemy/full stack react.jpg",
  },
  {
    provider: "Udemy",
    title: "Database Architecture Mastery (MySQL)",
    issuer: "Uday Academy",
    date: "Mei 2026",
    credentialId: "UC-806f4b45-0109-4c65-9720-389fff8ca068",
    credentialUrl: "https://ude.my/UC-806f4b45-0109-4c65-9720-389fff8ca068",
    image: "/images/sertifikasi/udemy/mastering mysql.jpg",
  },
  {
    provider: "Udemy",
    title: "Web Engineering Professional (MERN Stack)",
    issuer: "Uday Academy",
    date: "April 2026",
    credentialId: "UC-331781a3-53e7-4297-a84a-de9ef65219de",
    credentialUrl: "https://ude.my/UC-331781a3-53e7-4297-a84a-de9ef65219de",
    image: "/images/sertifikasi/udemy/web dev.jpg",
  },
  {
    provider: "Udemy",
    title: "Professional PHP & MySQL Backend Engineering",
    issuer: "Udemy Academy",
    date: "April 2026",
    credentialId: "UC-35fa32c4-5a8b-4d50-9508-624f38141e17",
    credentialUrl: "https://ude.my/UC-35fa32c4-5a8b-4d50-9508-624f38141e17",
    image: "/images/sertifikasi/udemy/php mysql.jpg",
  },
  {
    provider: "Udemy",
    title: "Master in Data Analysis and Analytics",
    issuer: "Udemy Academy",
    date: "April 2026",
    credentialId: "UC-7a2b3f0c-208c-4fdb-932e-b42276850549",
    credentialUrl: "https://ude.my/UC-7a2b3f0c-208c-4fdb-932e-b42276850549",
    image: "/images/sertifikasi/udemy/data analyst.jpg",
  },
  {
    provider: "Udemy",
    title: "Advanced Data Science Project Development",
    issuer: "Udemy Academy",
    date: "Maret 2026",
    credentialId: "UC-1d0ad384-1287-4aa0-afed-90441e5b1769",
    credentialUrl: "https://ude.my/UC-1d0ad384-1287-4aa0-afed-90441e5b1769",
    image: "/images/sertifikasi/udemy/data science.jpg",
  },
  {
    provider: "Udemy",
    title: "Advanced JavaScript: 20 Real-World Projects",
    issuer: "Udemy Academy",
    date: "April 2026",
    credentialId: "UC-1c74beb6-f05e-43a4-bf1c-42f43fae526c",
    credentialUrl: "https://ude.my/UC-1c74beb6-f05e-43a4-bf1c-42f43fae526c",
    image: "/images/sertifikasi/udemy/java script.jpg",
  },

  // --- KARIRNEX --- ✅ BARU
  {
    provider: "Karirnex",
    title: "Data Analyst Professional",
    issuer: "Karirnex",
    date: "2026",
    credentialId: "KARIRNEX-DA-001",
    credentialUrl: "#",
    image: "/images/sertifikasi/karirnex/Data Analyst.jpg",
  },
];

/* ─── EXPERIENCE ────────────────────────────────────────── */
export const EXPERIENCE = [
  {
    featured: true,
    badge: "Organization",
    badgeColor: { bg: "rgba(37,99,235,.12)", color: "#1d4ed8" },
    date: "2025 – 2026",
    title: "Public Relations Staff",
    org: "HIMASIFO UPN Veteran Jawa Timur",
    photo: "/images/experiences/hima/himasifo.jpg",
    photoAlt: "HIMASIFO UPN Veteran Jawa Timur",
    items: [
        "Actively participated in student association programs and events.",
        "Make a communication cooperation with the company and between universities.",
        "Developed leadership skills and strengthened team collaboration.",
    ],
    tags: ["Communication", "Leadership", "Teamwork"],
  },
  {
    featured: true,
    badge: "Organization",
    badgeColor: { bg: "rgba(37,99,235,.12)", color: "#1d4ed8" },
    date: "2024 – 2025",
    title: "Staff Ahli Website",
    org: "UKM Penalaran Dan Kreativitas",
    photo: "/images/experiences/ukmpnk/pnk.jpg",
    photoAlt: "UKM Penalaran PNK",
    items: [
        "Actively engaged in student reasoning and research activities.",
        "Building and maintaining the organization's website.",
        "Supported campus literacy programs and intellectual development initiatives.",
    ],
    tags: ["Creativity", "Academic", "Competition"],
  },
  {
    badge: "Internship",
    badgeColor: { bg: "rgba(37,99,235,.12)", color: "#1d4ed8" },
    date: "2022 – 2023",
    title: "Front-End Developer Intern",
    org: "CV Indra Protection",
    photo: "/images/experiences/magang/magang.jpg",
    photoAlt: "Front-End Developer Intern at CV Indra Protection",
    items: [
      "Developed responsive and accessible web interfaces.",
      "Translated design prototypes into clean, production-ready code.",
      "Optimized frontend performance and cross-browser compatibility.",
    ],
    tags: ["Front End", "UI/UX Desgin", "Team Project"],
  },
  {
    badge: "Organization",
    badgeColor: { bg: "rgba(37,99,235,.12)", color: "#1d4ed8" },
    date: "2026 – Present",
    title: "Novo Entrepreneurship",
    org: "Novo Club by Paragon Corp",
    photo: "/images/experiences/novo/novo.jpg",
    photoAlt: "Novo Entrepreneurship Program",
    items: [
      "Participating in intensive leadership and entrepreneurship program.",
      "Developing business mindset and strategic thinking skills.",
      "Networking with corporate leaders and industry experts.",
    ],
    tags: ["Leadership", "Entrepreneurship", "Problem Solving"],
  },
];